// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pet struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	Age       int32              `json:"age"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
